# Generated by Django 6.1.1 on 2026-10-02 03:24

import apps.seguridad.campos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', apps.seguridad.campos.CampoCifrado()),
                ('tratamiento', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('medicamentos', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'diagnósticos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedades', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('medicamentos_activos', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('operaciones', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('alergias', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'historiales médicos',
            },
        ),
    ]
