# Generated by Django 6.1.1 on 2026-10-02 03:24

import apps.seguridad.campos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(max_length=150)),
                ('laboratorio', models.CharField(max_length=150)),
                ('resultado', apps.seguridad.campos.CampoCifrado()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'resultados de exámenes',
                'ordering': ['-fecha'],
            },
        ),
    ]
