# Generated by Django 6.1.1 on 2026-10-02 03:24

import apps.seguridad.campos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', apps.seguridad.campos.CampoCifrado()),
                ('nombre', apps.seguridad.campos.CampoCifrado()),
                ('fecha_nacimiento', apps.seguridad.campos.CampoCifrado()),
                ('sexo', apps.seguridad.campos.CampoCifrado()),
                ('direccion', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('peso', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('estatura', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('email', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('telefono', apps.seguridad.campos.CampoCifrado(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
