# Generated by Django 6.1.1 on 2026-10-02 03:24

import apps.seguridad.campos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'previsión',
                'verbose_name_plural': 'previsiones',
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_cobertura', apps.seguridad.campos.CampoCifrado()),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='pacientes.paciente')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coberturas', to='convenios.prevision')),
            ],
            options={
                'verbose_name_plural': 'coberturas',
            },
        ),
    ]
